name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ windows-latest, ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build x86
      run: dotnet build -p:Configuration="Release" -p:Platform="x86" --no-restore
      timeout-minutes: 5
      
    # - name: Create Zip
    #   uses: papeloto/action-zip@v1
    #   if: a == 'B'
    # - name: Test
    #   run: dotnet test --no-restore --verbosity normal
